[[redirects]]
from = "https://algorust.netlify.app/*"
to = "https://algorust.dev/:splat"
status = 301
force = true

[[redirects]]
from = "https://algorust.com/*"
to = "https://algorust.dev/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
